//! Core types: identifiers, money, instruments, orders.

use rust_decimal::Decimal;
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use std::fmt;
use uuid::Uuid;

// =============================================================================
// Identifiers
// =============================================================================

/// Exchange identifier (e.g., "hyperliquid", "binance")
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct ExchangeId(pub String);

impl ExchangeId {
    pub fn new(s: impl Into<String>) -> Self {
        Self(s.into())
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl fmt::Display for ExchangeId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.0)
    }
}

/// Environment (mainnet vs testnet)
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize, JsonSchema)]
pub enum Environment {
    Mainnet,
    Testnet,
}

impl fmt::Display for Environment {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Mainnet => write!(f, "mainnet"),
            Self::Testnet => write!(f, "testnet"),
        }
    }
}

/// Unique key for an exchange instance: (exchange_id, environment)
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct ExchangeInstance {
    pub exchange_id: ExchangeId,
    pub environment: Environment,
}

impl ExchangeInstance {
    pub fn new(exchange_id: ExchangeId, environment: Environment) -> Self {
        Self {
            exchange_id,
            environment,
        }
    }
}

impl fmt::Display for ExchangeInstance {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}:{}", self.exchange_id, self.environment)
    }
}

/// Instrument identifier (your internal symbol key, e.g., "BTC-PERP")
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct InstrumentId(pub String);

impl InstrumentId {
    pub fn new(s: impl Into<String>) -> Self {
        Self(s.into())
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl fmt::Display for InstrumentId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.0)
    }
}

/// Exchange-specific market index (e.g., Hyperliquid asset index)
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct MarketIndex(pub u32);

impl MarketIndex {
    pub fn new(index: u32) -> Self {
        Self(index)
    }

    pub fn value(&self) -> u32 {
        self.0
    }
}

/// Client order ID - generated by us, globally unique
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct ClientOrderId(pub String);

impl ClientOrderId {
    pub fn new(s: impl Into<String>) -> Self {
        Self(s.into())
    }

    /// Generate a new unique client order ID (0x-prefixed hex UUID)
    pub fn generate() -> Self {
        Self(format!("0x{}", Uuid::new_v4().as_simple()))
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl fmt::Display for ClientOrderId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.0)
    }
}

/// Exchange order ID (returned by exchange on placement)
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct ExchangeOrderId(pub String);

impl ExchangeOrderId {
    pub fn new(s: impl Into<String>) -> Self {
        Self(s.into())
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl fmt::Display for ExchangeOrderId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.0)
    }
}

/// Trade ID from userFills (or derived stable fill key)
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct TradeId(pub String);

impl TradeId {
    pub fn new(s: impl Into<String>) -> Self {
        Self(s.into())
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl fmt::Display for TradeId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.0)
    }
}

/// Strategy identifier
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize, JsonSchema)]
pub struct StrategyId(pub String);

impl StrategyId {
    pub fn new(s: impl Into<String>) -> Self {
        Self(s.into())
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl fmt::Display for StrategyId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.0)
    }
}

/// Timer identifier
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct TimerId(pub u64);

impl TimerId {
    pub fn new(id: u64) -> Self {
        Self(id)
    }
}

// =============================================================================
// Money / Quantities
// =============================================================================

/// Price (fixed-point decimal)
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
pub struct Price(pub Decimal);

impl Price {
    pub fn new(d: Decimal) -> Self {
        Self(d)
    }

    pub fn from_str(s: &str) -> Result<Self, rust_decimal::Error> {
        Ok(Self(s.parse()?))
    }

    pub fn value(&self) -> Decimal {
        self.0
    }

    /// Round to tick size
    pub fn round_to_tick(&self, tick_size: Decimal) -> Self {
        if tick_size <= Decimal::ZERO {
            return *self;
        }
        let ticks = (self.0 / tick_size).round();
        Self(ticks * tick_size)
    }

    /// Trim to N significant digits (Hyperliquid requires max 5)
    pub fn trim_to_sig_figs(&self, digits: u32) -> Self {
        if self.0.is_zero() {
            return *self;
        }

        // Get the scale (number of decimal places)
        let s = format!("{}", self.0.abs());
        let parts: Vec<&str> = s.split('.').collect();

        // Count significant digits
        let int_part = parts[0].trim_start_matches('0');
        let sig_digits_in_int = int_part.len();

        if sig_digits_in_int >= digits as usize {
            // Integer part has enough sig figs, round there
            let scale = sig_digits_in_int - digits as usize;
            let factor = Decimal::new(10_i64.pow(scale as u32), 0);
            let rounded = (self.0 / factor).trunc() * factor;
            return Self(rounded);
        }

        // Need to include decimal places
        let decimal_scale = digits as usize - sig_digits_in_int;
        let rounded = self.0.round_dp(decimal_scale as u32);
        Self(rounded)
    }
}

impl fmt::Display for Price {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.0)
    }
}

impl From<Decimal> for Price {
    fn from(d: Decimal) -> Self {
        Self(d)
    }
}

/// Quantity (fixed-point decimal)
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
pub struct Qty(pub Decimal);

impl Qty {
    pub fn new(d: Decimal) -> Self {
        Self(d)
    }

    pub fn from_str(s: &str) -> Result<Self, rust_decimal::Error> {
        Ok(Self(s.parse()?))
    }

    pub fn value(&self) -> Decimal {
        self.0
    }

    pub fn is_zero(&self) -> bool {
        self.0.is_zero()
    }

    /// Round to lot size (standard rounding - suitable for buy orders)
    pub fn round_to_lot(&self, lot_size: Decimal) -> Self {
        if lot_size <= Decimal::ZERO {
            return *self;
        }
        let lots = (self.0 / lot_size).round();
        Self(lots * lot_size)
    }

    /// Truncate to lot size (floor - suitable for sell orders to avoid overselling)
    pub fn trunc_to_lot(&self, lot_size: Decimal) -> Self {
        if lot_size <= Decimal::ZERO {
            return *self;
        }
        let lots = (self.0 / lot_size).trunc();
        Self(lots * lot_size)
    }
}

impl fmt::Display for Qty {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.0)
    }
}

impl From<Decimal> for Qty {
    fn from(d: Decimal) -> Self {
        Self(d)
    }
}

impl std::ops::Add for Qty {
    type Output = Self;
    fn add(self, rhs: Self) -> Self::Output {
        Self(self.0 + rhs.0)
    }
}

impl std::ops::Sub for Qty {
    type Output = Self;
    fn sub(self, rhs: Self) -> Self::Output {
        Self(self.0 - rhs.0)
    }
}

impl std::ops::AddAssign for Qty {
    fn add_assign(&mut self, rhs: Self) {
        self.0 += rhs.0;
    }
}

// =============================================================================
// Assets / Balances
// =============================================================================

/// Asset identifier (e.g., "USDC", "BTC", "ETH")
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct AssetId(pub String);

impl AssetId {
    pub fn new(s: impl Into<String>) -> Self {
        Self(s.into())
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl fmt::Display for AssetId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.0)
    }
}

/// Balance for an asset
#[derive(Debug, Clone, Copy, Default, Serialize, Deserialize)]
pub struct Balance {
    pub total: Decimal,
    pub available: Decimal,
    pub reserved: Decimal,
}

impl Balance {
    pub fn new(total: Decimal, available: Decimal, reserved: Decimal) -> Self {
        Self {
            total,
            available,
            reserved,
        }
    }

    pub fn zero() -> Self {
        Self::default()
    }
}

/// Fee amount + currency
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Fee {
    pub amount: Decimal,
    pub asset: AssetId,
}

impl Fee {
    pub fn new(amount: Decimal, asset: AssetId) -> Self {
        Self { amount, asset }
    }

    pub fn zero(asset: AssetId) -> Self {
        Self {
            amount: Decimal::ZERO,
            asset,
        }
    }
}

// =============================================================================
// Instruments / Market Meta
// =============================================================================

/// Instrument kind
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum InstrumentKind {
    Spot,
    Perp,
}

/// Instrument metadata (provided by you, not discovered)
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InstrumentMeta {
    pub instrument_id: InstrumentId,
    pub market_index: MarketIndex,
    pub base_asset: AssetId,
    pub quote_asset: AssetId,
    pub tick_size: Decimal,
    pub lot_size: Decimal,
    pub min_qty: Option<Decimal>,
    pub min_notional: Option<Decimal>,
    pub fee_asset_default: Option<AssetId>,
    pub kind: InstrumentKind,
}

impl InstrumentMeta {
    /// Round a price to the instrument's tick size
    pub fn round_price(&self, price: Price) -> Price {
        price.round_to_tick(self.tick_size).trim_to_sig_figs(5)
    }

    /// Round a quantity to the instrument's lot size
    pub fn round_qty(&self, qty: Qty) -> Qty {
        qty.round_to_lot(self.lot_size)
    }

    /// Truncate a quantity DOWN to the instrument's lot size (floor)
    /// Use this for sell orders to avoid selling more than held
    pub fn trunc_qty(&self, qty: Qty) -> Qty {
        qty.trunc_to_lot(self.lot_size)
    }
}

// =============================================================================
// Orders
// =============================================================================

/// Order side
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum OrderSide {
    Buy,
    Sell,
}

impl OrderSide {
    pub fn opposite(&self) -> Self {
        match self {
            Self::Buy => Self::Sell,
            Self::Sell => Self::Buy,
        }
    }
}

impl fmt::Display for OrderSide {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Buy => write!(f, "BUY"),
            Self::Sell => write!(f, "SELL"),
        }
    }
}

/// Order type
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum OrderType {
    Limit,
    Market,
}

/// Time in force
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum TimeInForce {
    /// Good 'til canceled
    Gtc,
    /// Immediate or cancel
    Ioc,
    /// Fill or kill
    Fok,
}

impl Default for TimeInForce {
    fn default() -> Self {
        Self::Gtc
    }
}

/// Order status (engine-owned state machine)
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum OrderStatus {
    /// Order created locally, not yet submitted
    New,
    /// Order accepted by exchange
    Accepted,
    /// Order partially filled
    PartiallyFilled,
    /// Order fully filled (terminal)
    Filled,
    /// Order canceled (terminal)
    Canceled,
    /// Order rejected (terminal)
    Rejected,
}

impl OrderStatus {
    pub fn is_terminal(&self) -> bool {
        matches!(self, Self::Filled | Self::Canceled | Self::Rejected)
    }
}

/// Live order (engine's view of an order)
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LiveOrder {
    pub client_id: ClientOrderId,
    pub exchange_order_id: Option<ExchangeOrderId>,
    pub instrument: InstrumentId,
    pub side: OrderSide,
    pub price: Price,
    pub requested_qty: Qty,
    pub filled_qty: Qty,
    pub avg_fill_px: Option<Price>,
    pub status: OrderStatus,
    pub ts_created: i64,
    pub ts_last_update: i64,
}

impl LiveOrder {
    pub fn remaining_qty(&self) -> Qty {
        Qty(self.requested_qty.0 - self.filled_qty.0)
    }

    pub fn is_complete(&self) -> bool {
        self.filled_qty.0 >= self.requested_qty.0
    }
}

// =============================================================================
// Position
// =============================================================================

/// Position side (for display/logic)
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum PositionSide {
    Long,
    Short,
    Flat,
}

/// Position for an instrument (signed qty: positive=long, negative=short)
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Position {
    pub qty: Decimal, // signed: positive=long, negative=short
    pub avg_entry_px: Option<Price>,
    pub unrealized_pnl: Option<Decimal>,
    /// Accumulated realized PnL from closed trades
    #[serde(default)]
    pub realized_pnl: Decimal,
    /// Accumulated fees paid
    #[serde(default)]
    pub total_fees: Decimal,
}

impl Position {
    pub fn side(&self) -> PositionSide {
        if self.qty > Decimal::ZERO {
            PositionSide::Long
        } else if self.qty < Decimal::ZERO {
            PositionSide::Short
        } else {
            PositionSide::Flat
        }
    }

    pub fn is_flat(&self) -> bool {
        self.qty.is_zero()
    }

    pub fn abs_qty(&self) -> Decimal {
        self.qty.abs()
    }

    /// Compute total PnL: realized + unrealized - fees
    pub fn current_pnl(&self) -> Decimal {
        self.realized_pnl + self.unrealized_pnl.unwrap_or_default() - self.total_fees
    }
}

// =============================================================================
// Sync Mechanism
// =============================================================================

/// Strategy synchronization mechanism
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum SyncMechanism {
    /// Incremental: poll_user_fills() -> engine.apply_fill()
    Poll,
    /// Absolute: poll_account_state() -> engine.apply_snapshot()
    Snapshot,
}

impl Default for SyncMechanism {
    fn default() -> Self {
        Self::Poll
    }
}

/// Account state snapshot (absolute)
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AccountState {
    pub positions: Vec<PositionSnapshot>,
    pub account_value: Option<Decimal>,
    pub unrealized_pnl: Option<Decimal>,
}

/// Snapshot of a single position
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PositionSnapshot {
    pub instrument: InstrumentId,
    pub qty: Decimal,
    pub avg_entry_px: Option<Price>,
    pub unrealized_pnl: Option<Decimal>,
}

// =============================================================================
// Exchange Health
// =============================================================================

/// Exchange health state
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum ExchangeHealth {
    /// Exchange is available, reads/writes proceed normally
    Active,
    /// Exchange is unavailable (502 etc), reads continue with backoff, writes gated
    Halted,
}

impl Default for ExchangeHealth {
    fn default() -> Self {
        Self::Active
    }
}

// =============================================================================
// Quote
// =============================================================================

/// Best bid/ask quote
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Quote {
    pub instrument: InstrumentId,
    pub bid: Price,
    pub ask: Price,
    pub bid_size: Qty,
    pub ask_size: Qty,
    pub ts: i64,
}

impl Quote {
    pub fn mid(&self) -> Price {
        Price((self.bid.0 + self.ask.0) / Decimal::TWO)
    }

    pub fn spread(&self) -> Decimal {
        self.ask.0 - self.bid.0
    }

    pub fn spread_bps(&self) -> Decimal {
        if self.bid.0.is_zero() {
            return Decimal::ZERO;
        }
        (self.spread() / self.mid().0) * Decimal::new(10000, 0)
    }
}

// =============================================================================
// =============================================================================
// Timestamp helpers
// =============================================================================

/// Get current timestamp in milliseconds
#[cfg(not(feature = "wasm"))]
pub fn now_ms() -> i64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap()
        .as_millis() as i64
}

/// Get current timestamp in milliseconds (WASM version using js_sys)
#[cfg(feature = "wasm")]
pub fn now_ms() -> i64 {
    js_sys::Date::now() as i64
}
